version: "3"
services:
  python-hp:
    build:
      context: ..
      dockerfile: frontend/Dockerfile
    ports:
      - "22:22"
    volumes:
      - "./frontend:/usr/src/frontend/frontend"
    restart: always
