version: "3"
services:
  python-hp:
    build:
      context: ..
      dockerfile: frontend/Dockerfile
    ports:
      - "22:22"
    environment:
      # Regexes for allowed login combinations
      - SSH_ALLOWED_USERNAMES_REGEX=^[a-z_]([a-z0-9_-]{0,31}|[a-z0-9_-]{0,30}\$$)$$ # ($ escaped with $$)
      - SSH_ALLOWED_PASSWORDS_REGEX=^.{1,128}$$ # ($ escaped with $$)
      # Login success rate in percent after the above regexes are checked
      - SSH_LOGIN_SUCCESS_RATE
      - SSH_SERVER_PORT=22
      - SSH_LOCAL_VERSION=SSH-2.0-dropbear_2019.78 # SSH version reported by the honeypot
      - SSH_SESSION_TIMEOUT=600 # Timeout in seconds for when to treat an SSH connection inactive and end it
      # Timeout in seconds for when waiting for a TCP connection to appear
      # (5 seconds means it will check every five seconds if we want to shut it down)
      - SSH_SOCKET_TIMEOUT=5
      - SSH_MAX_UNACCEPTED_CONNECTIONS=100 # Max number of unacceped connections for the SSH socket
      - ENABLE_DEBUG_LOGGING=False
      - LOG_FILE=./frontend/honeypot.log # Log file to log to
      - BACKEND_ADDRESS # Address to backend
    volumes:
      - "./frontend:/usr/src/frontend/frontend"
    restart: always
