#!/bin/sh
# Utility used to generate RSA keys for the frontend

usage="usage: ./$(basename "$0") output_keyfile"
[ -z "$1" ] || [ "$#" -ne 1 ] && echo "$usage" && exit 1

openssl genrsa -out "$1".key 2048 && openssl rsa -in "$1".key -outform PEM -pubout -out "$1".pub.key
