version: "3"
services:
  python-controller:
    build: .
    ports:
      - "22:2222" # TODO
    volumes:
      - "./backend:/usr/src/backend/backend"
      - "/var/run/docker.sock:/var/run/docker.sock"