version: "3"
services:
  python-controller:
    build: .
    ports:
      - "80:80"
    volumes:
      - "/var/lib/docker:/var/lib/docker"
      - ".:/usr/src/backend"
      - "/var/run/docker.sock:/var/run/docker.sock"
