version: "3"
services:
  python-controller:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    environment:
      TARGET_SYSTEM_ADDRESS:
      KEEP_TARGET_SYSTEM_VOLUMES: "False"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
