version: "3"
services:
  python-controller:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
