# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import target_system_provider_pb2 as target__system__provider__pb2


class TargetSystemProviderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProvideTargetSystem = channel.unary_unary(
                '/target_system_provider.TargetSystemProvider/ProvideTargetSystem',
                request_serializer=target__system__provider__pb2.ProvisionRequest.SerializeToString,
                response_deserializer=target__system__provider__pb2.ProvisionResult.FromString,
                )
        self.YieldTargetSystem = channel.unary_unary(
                '/target_system_provider.TargetSystemProvider/YieldTargetSystem',
                request_serializer=target__system__provider__pb2.YieldRequest.SerializeToString,
                response_deserializer=target__system__provider__pb2.YieldResult.FromString,
                )


class TargetSystemProviderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProvideTargetSystem(self, request, context):
        """Provide a target system
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def YieldTargetSystem(self, request, context):
        """Request to stop an existing target system
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TargetSystemProviderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProvideTargetSystem': grpc.unary_unary_rpc_method_handler(
                    servicer.ProvideTargetSystem,
                    request_deserializer=target__system__provider__pb2.ProvisionRequest.FromString,
                    response_serializer=target__system__provider__pb2.ProvisionResult.SerializeToString,
            ),
            'YieldTargetSystem': grpc.unary_unary_rpc_method_handler(
                    servicer.YieldTargetSystem,
                    request_deserializer=target__system__provider__pb2.YieldRequest.FromString,
                    response_serializer=target__system__provider__pb2.YieldResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'target_system_provider.TargetSystemProvider', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TargetSystemProvider(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProvideTargetSystem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/target_system_provider.TargetSystemProvider/ProvideTargetSystem',
            target__system__provider__pb2.ProvisionRequest.SerializeToString,
            target__system__provider__pb2.ProvisionResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def YieldTargetSystem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/target_system_provider.TargetSystemProvider/YieldTargetSystem',
            target__system__provider__pb2.YieldRequest.SerializeToString,
            target__system__provider__pb2.YieldResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
