version: "3"

# docker-compose for starting a database, a frontend SSH server and a backend server
# starts the containers from ../database, ../frontend and ../backend

services:
  # Database, to which other containers can connect via "database" alias (instead of IP)
  postgres:
    image: "postgres:latest"
    container_name: "postgres"
    environment:
      POSTGRES_DB: "honeypot_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - "../database/database:/var/lib/postgresql/data"
      - "../database/config:/docker-entrypoint-initdb.d"
    networks:
      dev:
        aliases:
          - database
    restart: always

  # Frontend
  frontend:
    build:
      context: ..
      dockerfile: frontend/Dockerfile
    ports:
      - "22:22"
    volumes:
      - "../frontend/frontend:/usr/src/frontend/frontend"
    networks:
      dev:
        aliases:
          - frontend
    restart: always

  # Backend
  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      dev:
        aliases:
          - backend
    restart: always

# dev network
networks:
  dev:
