version: "2.1"
services:
  openssh-server:
    image: ghcr.io/linuxserver/openssh-server
    container_name: openssh-server
    hostname: mini-slav #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SUDO_ACCESS=true #optional
      - PASSWORD_ACCESS=true #optional
      - USER_PASSWORD=password #optional
      - USER_NAME=linuxserver.io #optional
    volumes:
      - ./containerstorage:/config
   

    ports:
      - 22:2222
    restart: unless-stopped
