# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: target_system_provider/target_system_provider.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='target_system_provider/target_system_provider.proto',
  package='target_system_provider',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n3target_system_provider/target_system_provider.proto\x12\x16target_system_provider\"4\n\x12\x41\x63quisitionRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\">\n\x11\x41\x63quisitionResult\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\r\"\x1a\n\x0cYieldRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\r\n\x0bYieldResult2\xe8\x01\n\x14TargetSystemProvider\x12n\n\x13\x41\x63quireTargetSystem\x12*.target_system_provider.AcquisitionRequest\x1a).target_system_provider.AcquisitionResult\"\x00\x12`\n\x11YieldTargetSystem\x12$.target_system_provider.YieldRequest\x1a#.target_system_provider.YieldResult\"\x00\x62\x06proto3'
)




_ACQUISITIONREQUEST = _descriptor.Descriptor(
  name='AcquisitionRequest',
  full_name='target_system_provider.AcquisitionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='target_system_provider.AcquisitionRequest.user', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='target_system_provider.AcquisitionRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=131,
)


_ACQUISITIONRESULT = _descriptor.Descriptor(
  name='AcquisitionResult',
  full_name='target_system_provider.AcquisitionResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='target_system_provider.AcquisitionResult.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='address', full_name='target_system_provider.AcquisitionResult.address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='target_system_provider.AcquisitionResult.port', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=195,
)


_YIELDREQUEST = _descriptor.Descriptor(
  name='YieldRequest',
  full_name='target_system_provider.YieldRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='target_system_provider.YieldRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=223,
)


_YIELDRESULT = _descriptor.Descriptor(
  name='YieldResult',
  full_name='target_system_provider.YieldResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=238,
)

DESCRIPTOR.message_types_by_name['AcquisitionRequest'] = _ACQUISITIONREQUEST
DESCRIPTOR.message_types_by_name['AcquisitionResult'] = _ACQUISITIONRESULT
DESCRIPTOR.message_types_by_name['YieldRequest'] = _YIELDREQUEST
DESCRIPTOR.message_types_by_name['YieldResult'] = _YIELDRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AcquisitionRequest = _reflection.GeneratedProtocolMessageType('AcquisitionRequest', (_message.Message,), {
  'DESCRIPTOR' : _ACQUISITIONREQUEST,
  '__module__' : 'target_system_provider.target_system_provider_pb2'
  # @@protoc_insertion_point(class_scope:target_system_provider.AcquisitionRequest)
  })
_sym_db.RegisterMessage(AcquisitionRequest)

AcquisitionResult = _reflection.GeneratedProtocolMessageType('AcquisitionResult', (_message.Message,), {
  'DESCRIPTOR' : _ACQUISITIONRESULT,
  '__module__' : 'target_system_provider.target_system_provider_pb2'
  # @@protoc_insertion_point(class_scope:target_system_provider.AcquisitionResult)
  })
_sym_db.RegisterMessage(AcquisitionResult)

YieldRequest = _reflection.GeneratedProtocolMessageType('YieldRequest', (_message.Message,), {
  'DESCRIPTOR' : _YIELDREQUEST,
  '__module__' : 'target_system_provider.target_system_provider_pb2'
  # @@protoc_insertion_point(class_scope:target_system_provider.YieldRequest)
  })
_sym_db.RegisterMessage(YieldRequest)

YieldResult = _reflection.GeneratedProtocolMessageType('YieldResult', (_message.Message,), {
  'DESCRIPTOR' : _YIELDRESULT,
  '__module__' : 'target_system_provider.target_system_provider_pb2'
  # @@protoc_insertion_point(class_scope:target_system_provider.YieldResult)
  })
_sym_db.RegisterMessage(YieldResult)



_TARGETSYSTEMPROVIDER = _descriptor.ServiceDescriptor(
  name='TargetSystemProvider',
  full_name='target_system_provider.TargetSystemProvider',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=241,
  serialized_end=473,
  methods=[
  _descriptor.MethodDescriptor(
    name='AcquireTargetSystem',
    full_name='target_system_provider.TargetSystemProvider.AcquireTargetSystem',
    index=0,
    containing_service=None,
    input_type=_ACQUISITIONREQUEST,
    output_type=_ACQUISITIONRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='YieldTargetSystem',
    full_name='target_system_provider.TargetSystemProvider.YieldTargetSystem',
    index=1,
    containing_service=None,
    input_type=_YIELDREQUEST,
    output_type=_YIELDRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TARGETSYSTEMPROVIDER)

DESCRIPTOR.services_by_name['TargetSystemProvider'] = _TARGETSYSTEMPROVIDER

# @@protoc_insertion_point(module_scope)
