version: "3"

services:
  postgres:
    image: "postgres:latest"
    container_name: "postgres"
    environment: 
      POSTGRES_DB: "honeypot_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - "./database:/var/lib/postgresql/data"
      - "./config:/docker-entrypoint-initdb.d"
    restart: always
