name: Python tests

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        working-directory: ./frontend/
        run: |
          sudo npm install -g pyright
          pip install poetry
          poetry install

      - name: Generate RSA keys
        working-directory: ./frontend/
        run: ./genkeys

      - name: Pylint
        if: always()
        working-directory: ./frontend/
        run: |
          . .venv/bin/activate
          pylint --fail-under 7 frontend

      - name: Pyright
        if: always()
        working-directory: ./frontend/
        run: |
          . .venv/bin/activate
          pyright

      - name: Pytest
        if: always()
        working-directory: ./frontend/
        run: |
          . .venv/bin/activate
          pytest

  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: docker-practice/actions-setup-docker@master
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        working-directory: ./backend/
        run: |
          sudo npm install -g pyright
          pip install poetry
          poetry install

      - name: Pylint
        if: always()
        working-directory: ./backend/
        run: |
          . .venv/bin/activate
          pylint  --fail-under 7 backend

      - name: Pyright
        if: always()
        working-directory: ./backend/
        run: |
          . .venv/bin/activate
          pyright

      - name: Pytest
        if: always()
        working-directory: ./backend/
        run: |
          . .venv/bin/activate
          pytest
