name: Python tests

on:
  pull_request:
    branches: [ main ]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
           python-version: 3.9
           
      - name: Install poetry
        run: pip install poetry
        
      - name: Install python dependencies
        working-directory: ./frontend/
        run: poetry install
          
      - name: Generate RSA keys
        working-directory: ./frontend/
        run: ./genkeys
        
      - name: Frontend linting
        working-directory: ./frontend/
        run: |
          . .venv/bin/activate
          pylint frontend --exit-zero
          
      - name: Frontend tests
        working-directory: ./frontend/
        run: |
          . .venv/bin/activate
          pytest

  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: docker-practice/actions-setup-docker@master
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
           python-version: 3.9

      - name: Install poetry
        run: pip install poetry

      - name: Install python dependencies
        working-directory: ./backend/
        run: poetry install

      - name: Backend linting
        working-directory: ./backend/
        run: |
          . .venv/bin/activate
          pylint backend --exit-zero
          
      - name: Backend tests
        working-directory: ./backend/
        run: |
          . .venv/bin/activate
          pytest
